# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d3d366c21b236b440ea6cb3008ecbe9e2edc25d5d0aa4e6ae1876e52d708a41487c470822d9a58f5cad8c3c2feb66b3c00c8cdc064dbe33065774bc67d29cd7

test:
  secret_key_base: 2bc6597d61721e5ab69b8e1ec242ffacc6583212b827edb99a4ae53494c97ffb54d38f8a40515f90f5a2abfa63ff3165f4b124625c1fc64850f0fb1a1cc69b6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
